# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'num_layout.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 447)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/c.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sell1 = QtWidgets.QPushButton(self.centralwidget)
        self.sell1.setGeometry(QtCore.QRect(390, 60, 221, 131))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sell1.setFont(font)
        self.sell1.setText("")
        self.sell1.setIcon(icon)
        self.sell1.setIconSize(QtCore.QSize(600, 100))
        self.sell1.setObjectName("sell1")
        self.TotalLabel = QtWidgets.QLabel(self.centralwidget)
        self.TotalLabel.setGeometry(QtCore.QRect(360, 360, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.TotalLabel.setFont(font)
        self.TotalLabel.setObjectName("TotalLabel")
        self.TotalNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.TotalNumber.setGeometry(QtCore.QRect(470, 350, 141, 71))
        self.TotalNumber.setObjectName("TotalNumber")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 341, 301))
        self.groupBox.setObjectName("groupBox")
        self.helm = QtWidgets.QPushButton(self.groupBox)
        self.helm.setGeometry(QtCore.QRect(140, 20, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.helm.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../img/helm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helm.setIcon(icon1)
        self.helm.setIconSize(QtCore.QSize(63, 55))
        self.helm.setObjectName("helm")
        self.brust = QtWidgets.QPushButton(self.groupBox)
        self.brust.setGeometry(QtCore.QRect(140, 100, 91, 111))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.brust.setFont(font)
        self.brust.setAutoFillBackground(False)
        self.brust.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../img/chest.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brust.setIcon(icon2)
        self.brust.setIconSize(QtCore.QSize(63, 63))
        self.brust.setFlat(False)
        self.brust.setObjectName("brust")
        self.amulett = QtWidgets.QPushButton(self.groupBox)
        self.amulett.setGeometry(QtCore.QRect(240, 20, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.amulett.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../img/amulet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.amulett.setIcon(icon3)
        self.amulett.setIconSize(QtCore.QSize(50, 35))
        self.amulett.setObjectName("amulett")
        self.waffe = QtWidgets.QPushButton(self.groupBox)
        self.waffe.setGeometry(QtCore.QRect(40, 100, 91, 111))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.waffe.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../img/axe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.waffe.setIcon(icon4)
        self.waffe.setIconSize(QtCore.QSize(6666, 90))
        self.waffe.setObjectName("waffe")
        self.ring = QtWidgets.QPushButton(self.groupBox)
        self.ring.setGeometry(QtCore.QRect(240, 130, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.ring.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../img/ring.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ring.setIcon(icon5)
        self.ring.setIconSize(QtCore.QSize(35, 35))
        self.ring.setObjectName("ring")
        self.hand = QtWidgets.QPushButton(self.groupBox)
        self.hand.setGeometry(QtCore.QRect(40, 220, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.hand.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../img/gloves.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hand.setIcon(icon6)
        self.hand.setIconSize(QtCore.QSize(63, 55))
        self.hand.setObjectName("hand")
        self.gurtel = QtWidgets.QPushButton(self.groupBox)
        self.gurtel.setGeometry(QtCore.QRect(140, 250, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.gurtel.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../img/belts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gurtel.setIcon(icon7)
        self.gurtel.setIconSize(QtCore.QSize(55, 40))
        self.gurtel.setObjectName("gurtel")
        self.schuh = QtWidgets.QPushButton(self.groupBox)
        self.schuh.setGeometry(QtCore.QRect(240, 220, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.schuh.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../img/boots.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.schuh.setIcon(icon8)
        self.schuh.setIconSize(QtCore.QSize(63, 50))
        self.schuh.setObjectName("schuh")
        self.sell2 = QtWidgets.QPushButton(self.centralwidget)
        self.sell2.setGeometry(QtCore.QRect(390, 210, 221, 131))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sell2.setFont(font)
        self.sell2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../img/2c_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sell2.setIcon(icon9)
        self.sell2.setIconSize(QtCore.QSize(600, 100))
        self.sell2.setObjectName("sell2")
        self.groupBox.raise_()
        self.sell1.raise_()
        self.TotalLabel.raise_()
        self.TotalNumber.raise_()
        self.sell2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chaos Recipe Tracker"))
        MainWindow.setAccessibleName(_translate("MainWindow", "Chaos Recipe Tracker"))
        self.TotalLabel.setText(_translate("MainWindow", "Total:"))
        self.groupBox.setTitle(_translate("MainWindow", "Inventory"))
        self.helm.setText(_translate("MainWindow", "0"))
        self.brust.setText(_translate("MainWindow", "0"))
        self.amulett.setText(_translate("MainWindow", "0"))
        self.waffe.setText(_translate("MainWindow", "0"))
        self.ring.setText(_translate("MainWindow", "0"))
        self.hand.setText(_translate("MainWindow", "0"))
        self.gurtel.setText(_translate("MainWindow", "0"))
        self.schuh.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

